version: '3.9'

services:
  database:
    image: postgres
    container_name: database_cicd
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cicd_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: cicd
    ports:
      - 4444:4444
    volumes:
      - .:/usr/app
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
